### PR TITLE
Version 0.1.1

### LINKED ISSUE #4: Release version 0.1.1
Once we've made all preparations for open sourcing this, we can release version 0.1.1 to capture those changes.

### PR DESCRIPTION
**Pull request by Narnach**
Our main branch is protected (useful feature!) but that means I need to create a PR to bump the version.

The commit in this PR (d4b3f4fd5c444089c0b4aadbabdb0c2c29f3ae37) is tagged with `v0.1.1` so please _don't_ use a squash merge for this because that breaks the tag. Use a regular merge instead.

This resolves #4.

### CODE REVIEW

**Review by wvengen — APPROVED** [review]
Hooray!

**Comment by Narnach** [comment]
Eh... you squashed my merge so the tag was broken (pointing to an orphan commit you rewrote by squashing).
I managed to fix it by force-pushing a new tag based on the actual commit that's part of `main` now.

Would you be open to disable squash merges in this repo?
Their history rewriting properties conflicts with release tags. Because release tags are not visible in a PR it's easy to miss that you broken them.

**Comment by wvengen** [comment]
Ouch. I did check, but perhaps I still did the wrong thing. Sorry!
I'll disable squash merges.

**Comment by Narnach** [comment]
I wanted to create a tag for a "Version 0.1.1" release commit and push that to `main`, but we can't push to main.
So plan B was to create a branch and push that commit to the branch, which also pushed the tag.
If the PR was merged with a _regular_ merge, then the tagged commit would have become part of the history of `main` and it was all fine. By squashing the commit history got rewritten and thus a _different commit_ became part of the `main` history and thus the tag broke.

My issue with tagging after merge is that it's a separate step that's easily forgotten if it's not one person doing everything in one go. I've gotten annoyed at plenty of repositories that have a sloppy release tagging policy, so I tend to pay extra attention to it.

**Comment by wvengen** [comment]
I see that tagging is an extra step.
Perhaps we could have a Github Action that only runs when file [`lib/questionmark/barcodes/version.rb`](https://github.com/q-m/questionmark-barcodes/blob/main/lib/questionmark/barcodes/version.rb) was changed, which creates a tag?

**Comment by Narnach** [comment]
Maybe... I did a quick search but there are a lot of actions that mention tags, but they seem to have their own quirks.

Maybe it's possible to solve this with a script in a custom github action? If feels like such a minor thing to "waste" time on.

**Pull request merged**
